[package]
name = "unisock-smol-tungstenite"
version = "0.1.0"
edition = "2021"

[dependencies]
async-io = "2.3"
futures-lite = "2.3"
socket2 = { version = "0.5", features = ["all"] }
unisock = { version = "0.1", path = "../../" }
async-tungstenite = "0.26"
futures-sink = "0.3"

[lints]
workspace = true

[features]
